# Generated by Django 3.2 on 2023-08-31 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='todo_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
